version: '3'
services:
  backend:
    container_name: backend
    build: ./back
    ports:
      - '2023:2023'
    restart: always
    networks:
      - local
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - './data:/data/db'
    ports:
      - '27017:27017'
    networks:
      - local
    command: --quiet
networks:
  local:
    driver: bridge
